##服务器端口号
server:
  port: 8085
##dubbo 注册到注册中心的名称
dubbo:
  application:
    name: user-consumer
  registry:
    ## dubbo注册中心地址 zookeeper地址
    address: zookeeper://47.96.7.143:2181

shenyu:
  client:
    register-type: zookeeper
    server-lists: 47.96.7.143:2181
    props:
      contextPath: /user
      appName: user-consumer
      port: 8085

# 端口
spring:
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 11
    # Redis服务器地址
    host: 47.96.7.143
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
