#Dubbo
dubbo:
  application:
    #dubbo 注册到注册中心的名称
    name: post-provier
  #采用协议方式和端口号
  protocol:
    name: dubbo
    port: 20888
  registry:
    # dubbo注册中心地址 zookeeper地址
    address: zookeeper://47.96.7.143:2181
  scan:
    # 实现类扫包范围(可以省略，dubbo会自动扫)
    base-packages: top.greatbiscuit.hyxk.serviceImpl

#shenyu
shenyu:
  client:
    register-type: zookeeper
    server-lists: 47.96.7.143:2181
    props:
      contextPath: /post-public
      appName: post-provier
      port: 20888
  dubbo:
    #多参数类型支持
    parameter: multi

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.7.143:3306/hyxk?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: hyxk
    password: Lyx010128.
    type: com.alibaba.druid.pool.DruidDataSource
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 6
    # Redis服务器地址
    host: 47.96.7.143
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.greatbiscuit.hyxk.entity
  configuration:
    # 自动生成主键
    use-generated-keys: true
    # 字段大小写区分（驼峰式）
    map-underscore-to-camel-case: true



